# Generated by Django 4.0.3 on 2022-03-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.IntegerField()),
                ('fullName', models.CharField(max_length=35)),
                ('age', models.IntegerField()),
                ('doB', models.DateField()),
                ('position', models.CharField(max_length=20)),
                ('phoneNo', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=50)),
                ('stateOfOrigin', models.CharField(max_length=10)),
                ('employmentDate', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
