# Generated by Django 4.0.3 on 2022-03-10 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashierID', models.IntegerField()),
                ('stationStart', models.DateTimeField(auto_now_add=True)),
                ('stationEnd', models.DateTimeField(auto_now_add=True)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordersID', models.IntegerField()),
                ('orderDate', models.DateField()),
                ('qtyOrdered', models.IntegerField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productsID', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=30)),
                ('Barcode', models.IntegerField()),
                ('ExpiryDate', models.DateField()),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.IntegerField()),
                ('paymentMethod', models.CharField(max_length=10)),
                ('totalAmount', models.IntegerField()),
                ('noOfPurchasedItems', models.IntegerField()),
                ('paidAt', models.DateTimeField(auto_now_add=True)),
                ('cashierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.cashier')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliersID', models.IntegerField()),
                ('suppliersName', models.CharField(max_length=25)),
                ('suppliersAddress', models.CharField(max_length=25)),
                ('suppliersContact', models.CharField(max_length=11)),
                ('ordersID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.orders')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTypeID', models.IntegerField()),
                ('productType', models.CharField(max_length=20)),
                ('productsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='productsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products'),
        ),
    ]
