# Generated by Django 4.0.3 on 2022-04-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='employeeID',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='productsID',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='productsID',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='ordersID',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
