# Generated by Django 4.0.3 on 2022-04-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_orders_products_suppliers_producttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='productsID',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='ordersID',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
