# Generated by Django 4.0.3 on 2022-04-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_producttype_suppliers_products_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
    ]
