# Generated by Django 4.0.3 on 2022-04-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_products_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemCount',
        ),
    ]
