# Generated by Django 4.0.3 on 2022-04-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_sales_quantity_sales_noofitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='paymentMethod',
            field=models.CharField(default='cash', max_length=10),
        ),
    ]
