# Generated by Django 4.0.3 on 2022-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_producttype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productsID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
