# Generated by Django 4.0.3 on 2022-04-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_transactions_cashierid_employee_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='employeeID',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
