# Generated by Django 4.0.3 on 2022-05-01 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_employee_profile_pic_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSalesAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtybought', models.IntegerField(default=0)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
                ('salesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sales')),
            ],
        ),
    ]
