# Generated by Django 4.0.3 on 2022-05-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_productsalesat_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsalesat',
            name='price',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
