# Generated by Django 4.0.3 on 2022-05-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_productsalesat_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsalesat',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
