# Generated by Django 4.0.3 on 2022-05-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_productsalesat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='min_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='order_quantity',
            field=models.IntegerField(default=5),
        ),
    ]
